### ISSUE TITLE
Aljibe installation in Drupal 11 is installing PHP 8.2 but 8.3 is required

### ISSUE THREAD

**Issue by omarlopesino** [Metadrop/ddev-aljibe#31]
When I install a Drupal 11 through Aljibe I have the following error:

![image](https://github.com/user-attachments/assets/8c2d486a-c1a8-408a-834e-5a8d377d9e34)

The main error is:

```
 drupal/core[11.0.0-alpha1, ..., 11.x-dev] require php >=8.3.0 -> your php version (8.2.24) does not satisfy that requirement.
````

## Steps to reproduce

```
ddev config --auto
ddev add-on get metadrop/ddev-aljibe
ddev aljibe-assistant
```

When it asks for the drupal version, choose 11.

**Comment by rfay** [comment]
You are using an old version of DDEV, please update. PHP 8.3 is now the default in DDEV v1.24+

**Comment by omarlopesino** [comment]
Many thanks! After upgrading both PHP and ddev , now when I run `ddev config --auto`  it sets PHP 8.3 at config.yaml. So the problem is solved.

I've posted the issue because I didn't have this problem the last week doing the same actions, but however the problem was on my side.

Closing.
