### ISSUE TITLE
HEAD version of ddev uses add-on get command instead of only get

### ISSUE THREAD

**Issue by juanjol** [Metadrop/ddev-aljibe#6]
Looks like the next release of ddev will deprecate the ddev get command and will be replaced with ddev add-on get command.

Aljibe must support both, and tests must be adapted for the version that Aljibe is running. 

Test with HEAD version of ddev must be enabled again (look on previous commits to see how to enable it, and enable only on test step, not in code quality step).

**Comment by rfay** [comment]
`ddev get` will still work for a long time.

**Comment by juanjol** [comment]
Hi @rfay, thanks for your comment! As far as I could see the tests were failing when run against HEAD version of ddev, so I created this issue to check if that was really the problem, and so I don't forget to re-run the tests against that version to ensure compatibility with future versions.

I'm going to work on this again to see what was really going on.

**Comment by rfay** [comment]
If there's a problem with DDEV HEAD it is probably something wrong with DDEV, so check carefully, thanks.

**Comment by juanjol** [comment]
Now we use "ddev add-on get" command, closing this!
